apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: colpetty-guardian-staging
  namespace: argocd
  labels:
    app: colpetty-guardian
    environment: staging
spec:
  project: default
  source:
    repoURL: https://github.com/kaveeshag/batman-colpetty-demo.git
    targetRevision: main
    path: k8s-manifests/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: colpetty-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10

# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: colpetty-guardian-production
#   namespace: argocd
#   labels:
#     app: colpetty-guardian
#     environment: production
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/kaveeshag/batman-colpetty-demo.git
#     targetRevision: main
#     path: k8s-manifests/overlays/production
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: colpetty-production
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#       allowEmpty: false
#     syncOptions:
#       - CreateNamespace=true
#       - PrunePropagationPolicy=foreground
#       - PruneLast=true
#     retry:
#       limit: 5
#       backoff:
#         duration: 5s
#         factor: 2
#         maxDuration: 3m
#   revisionHistoryLimit: 10