apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: colpetty-production

patchesStrategicMerge:
  - replica-patch.yaml

commonLabels:
  environment: production

configMapGenerator:
  - name: batman-config
    behavior: merge
    literals:
      - environment=production
      - debug=false