apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: colpetty-production

images:
- name: batman-app
  newName: ghcr.io/kaveeshag/batman-colpetty-demo
  newTag: batman-cfde5d2
  
patchesStrategicMerge:
- replica-patch.yaml

commonLabels:
  environment: production

configMapGenerator:
- behavior: merge
  literals:
  - environment=production
  - debug=false
  name: batman-config
