name: Batman CI/CD Pipeline

on:
  push:
    branches: [ main ]
    paths: 
      - 'app/**'
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    outputs:
      image-tag: ${{ steps.meta.outputs.tags }}
      image-digest: ${{ steps.build.outputs.digest }}
    
    steps:
    - name: Checkout Batman's Code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata for Batman's App
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix=batman-

    - name: Build and Push Batman's Image
      id: build
      uses: docker/build-push-action@v5
      with:
        context: ./app
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  update-manifests:
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - name: Checkout Manifest Repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: main
        fetch-depth: 0

    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v2

    - name: Debug - Show image tag
      run: |
        echo "Full image tag from build job: ${{ needs.build-and-push.outputs.image-tag }}"
        echo "Repository: ${{ github.repository }}"
        echo "SHA: ${{ github.sha }}"
        echo "Current branch: $(git branch --show-current)"

    - name: Update Image Tag in Staging
      run: |
        cd k8s-manifests/overlays/staging
        # Use the commit SHA as the tag
        IMAGE_TAG="batman-$(echo ${{ github.sha }} | head -c7)"
        echo "Using image tag: ${IMAGE_TAG}"
        kustomize edit set image batman-app=ghcr.io/${{ github.repository }}:${IMAGE_TAG}
        echo "Updated staging kustomization.yaml:"
        cat kustomization.yaml
        
    - name: Update Image Tag in Production
      run: |
        cd k8s-manifests/overlays/production
        # Use the commit SHA as the tag
        IMAGE_TAG="batman-$(echo ${{ github.sha }} | head -c7)"
        echo "Using image tag: ${IMAGE_TAG}"
        kustomize edit set image batman-app=ghcr.io/${{ github.repository }}:${IMAGE_TAG}
        echo "Updated production kustomization.yaml:"
        cat kustomization.yaml

    - name: Commit and Push Updates
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "🦇 Update image to batman-${{ github.sha }}"
        branch: main
        file_pattern: k8s-manifests/
        commit_user_name: KaveeshaG
        commit_user_email: uakaveeshagimhana@gmail.com
        commit_author: KaveeshaG <uakaveeshagimhana@gmail.com>