name: Batman CI/CD Pipeline

on:
  push:
    branches: [ main ]
    paths: 
      - 'app/**'
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    outputs:
      image-tag: ${{ steps.meta.outputs.tags }}
      image-digest: ${{ steps.build.outputs.digest }}
    
    steps:
    - name: Checkout Batman's Code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata for Batman's App
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix=batman-

    - name: Build and Push Batman's Image
      id: build
      uses: docker/build-push-action@v5
      with:
        context: ./app
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  update-manifests:
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - name: Checkout Manifest Repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v2

    - name: Extract Image Tag
      id: extract-tag
      run: |
        # Extract just the tag from the full image reference
        TAG=$(echo "${{ needs.build-and-push.outputs.image-tag }}" | cut -d':' -f2)
        echo "tag=${TAG}" >> $GITHUB_OUTPUT

    - name: Update Image Tag in Staging
      run: |
        cd k8s-manifests/overlays/staging
        kustomize edit set image batman-app=ghcr.io/${{ github.repository }}:${{ steps.extract-tag.outputs.tag }}
        
    - name: Update Image Tag in Production
      run: |
        cd k8s-manifests/overlays/production
        kustomize edit set image batman-app=ghcr.io/${{ github.repository }}:${{ steps.extract-tag.outputs.tag }}

    - name: Commit and Push Updates
      run: |
        git config --local user.email "batman@gotham.city"
        git config --local user.name "Batman Bot"
        git add k8s-manifests/
        git diff --staged --quiet || git commit -m "🦇 Update image to ${{ steps.extract-tag.outputs.tag }}"
        git push